CONFIG_PATH = r"C:\LDPlayer\LDPlayer9\vms\config"
PACKAGE_NAME = "com.smilegate.chaoszero.stove.google"
SCREENSHOT_DIR = r"C:/Users/Killua/Desktop/Chaos/screenshots"
TEMPLATE_DIR = r"C:/Users/Killua/Desktop/Chaos/templates"
MAIN_PATH = "C:/Users/Killua/Desktop/Chaos/"
APK_DIR = r"C:/Users/Killua/Desktop/Chaos/ChaosAPK"
ASSETS_DIR = r"C:\Users\Killua\Desktop\accounts\external"

# CONFIG_PATH = r"D:\LDPlayer\LDPlayer9\vms\config"
# PACKAGE_NAME = "com.smilegate.chaoszero.stove.google"
# SCREENSHOT_DIR = r"C:\Users\Administrator\Desktop\Chaos\screenshots"
# MAIN_PATH = "C:/Users/Administrator/Desktop/Chaos/"
# APK_DIR = r"C:/Users/Administrator/Desktop/Chaos/ChaosAPK"
# ASSETS_DIR = r"C:\Users\Administrator\Desktop\Chaos\accounts\external"